// NOTE: intentionally NOT a "use client" module. The scoring math is pure
// (no browser APIs), so the server-side risk oracle imports it too and both
// sides produce identical scores.

import calibration from "./riskCalibration.js";

/**
 * Lightweight Risk Scoring Model
 * Browser-based logistic regression for risk score calculation
 * Uses the 4 metrics from Horizon data to calculate 0-100 risk score
 */

/**
 * Pre-trained model weights (simplified logistic regression)
 * These weights are trained on a hypothetical dataset of good/risky behaviors
 */
const MODEL_WEIGHTS = {
  // Feature weights (how much each metric affects risk).
  // Signs encode direction; magnitudes are scaled so the sigmoid actually spans
  // the full 0-100 range across realistic profiles. With the previous magnitudes
  // (and bias 0.45) every input collapsed into ~48-67, i.e. the model could never
  // assign TIER_1 or TIER_3 — the original weight ratios are preserved here.
  totalVolume: -0.375, // Higher volume = lower risk (up to a point)
  uniqueCounterparties: -0.625, // More diverse counterparties = lower risk
  assetDiversity: -0.5, // More asset variety = lower risk
  nightDayRatio: 0.875, // More night activity = higher risk

  // Interaction weights (combined effects)
  volumeCounterpartyInteraction: -0.25, // High volume + high counterparties = very low risk

  // Bias term
  bias: 0.35,
};

/**
 * Feature normalization — empirical, not invented.
 *
 * Each raw feature is mapped to its PERCENTILE in the real Stellar wallet
 * population (riskCalibration.json, regenerated by
 * `node scripts/calibrate-risk-model.mjs`).
 *
 * This replaced hand-picked min/max bounds (totalVolume max 10_000,
 * assetDiversity max 10, ...). Measured against real mainnet wallets those
 * bounds were wrong by 3-3300x, so `min(1, value/(max-min))` saturated: ~88% of
 * real wallets clamped totalVolume to exactly 1.0 and ~83% clamped
 * assetDiversity, turning both features into constants. ~92% of real wallets
 * ended up in TIER_2.
 *
 * Percentile mapping is invariant under monotone transforms, so it absorbs the
 * heavy tails (volume spans ~10 orders of magnitude) without log-scaling and
 * cannot saturate.
 */
const CALIBRATION_GRID = calibration.quantileGrid;

/**
 * Map a raw value to its percentile (0-1) via linear interpolation between the
 * calibrated quantile points.
 */
function percentileOf(value, quantiles) {
  if (!Number.isFinite(value)) return 0;
  if (value <= quantiles[0]) return 0;
  if (value >= quantiles[quantiles.length - 1]) return 1;

  for (let i = 1; i < quantiles.length; i++) {
    if (value <= quantiles[i]) {
      const lo = quantiles[i - 1];
      const hi = quantiles[i];
      const frac = hi === lo ? 0 : (value - lo) / (hi - lo);
      return CALIBRATION_GRID[i - 1] + (CALIBRATION_GRID[i] - CALIBRATION_GRID[i - 1]) * frac;
    }
  }
  return 1;
}

/**
 * Raw weighted composite (sigmoid output) for a wallet's metrics.
 *
 * Depends only on the per-feature quantiles, never on the composite table, so
 * the calibration script can import it to build that table without a cycle.
 */
export function riskComposite(metrics) {
  return calculateLogisticRegression(normalizeFeatures(metrics));
}

/**
 * Calculate risk score from transaction metrics
 * @param {Object} metrics - Transaction metrics from Horizon
 * @returns {Object} Risk analysis result
 */
export function calculateRiskScore(metrics) {
  if (!metrics || typeof metrics !== 'object') {
    console.error('calculateRiskScore: metrics must be a non-null object');
    return fallbackRiskCalculation({});
  }

  try {
    // Normalize features to 0-1 range
    const normalizedFeatures = normalizeFeatures(metrics);

    // Calculate logistic regression output
    const logitScore = calculateLogisticRegression(normalizedFeatures);

    // Convert to a 0-100 risk score.
    //
    // MODEL_WEIGHTS are signed so risky behaviour (nightDayRatio) pushes the
    // composite UP and safe behaviour (volume/counterparties/asset diversity)
    // pushes it DOWN, so the sigmoid already yields P(risky) — it is NOT
    // inverted (an earlier version returned `(1 - logitScore) * 100`, which gave
    // risky wallets LOW scores).
    //
    // The composite is then mapped to its PERCENTILE among real Stellar wallets.
    // A weighted sum of ~independent features concentrates around its mean (CLT)
    // and the sigmoid compresses further, so the raw composite put ~96% of real
    // wallets in TIER_2. The percentile mapping makes the score uniform over the
    // population by construction, so the 30/70 tier thresholds actually split it.
    const riskScore = calibration.composite
      ? Math.round(
          Math.max(0, Math.min(100, percentileOf(logitScore, calibration.composite) * 100))
        )
      : Math.round(Math.max(0, Math.min(100, logitScore * 100)));

    // Determine tier based on risk score
    const tier = calculateTier(riskScore);

    // Calculate feature importance for explanation
    const featureImportance = calculateFeatureImportance(
      normalizedFeatures,
      metrics
    );

    // "No history" is NOT "high risk" — it is unknown. A brand-new wallet has
    // every feature at the bottom of the population, which the composite reads
    // as a risky profile (it scored 87/TIER_3). Surface the distinction instead
    // of laundering absence of evidence into evidence of risk.
    const dataQuality = getDataQualityScore(metrics);
    const insufficientData = dataQuality.needsMoreData;

    const result = {
      riskScore,
      tier,
      dataQuality,
      insufficientData,
      confidence: calculateConfidence(normalizedFeatures, metrics),
      featureImportance,
      explanation: generateExplanation(riskScore, featureImportance),
      recommendations: generateRecommendations(featureImportance),
      rawMetrics: metrics,
      normalizedFeatures,
      modelVersion: "2.0.0-empirical",
    };

    return result;
  } catch (error) {
    console.error("❌ ML calculation failed:", error);

    // Fallback to simple rule-based scoring
    return fallbackRiskCalculation(metrics);
  }
}

/**
 * Normalize features to 0-1 range for ML model
 */
function normalizeFeatures(metrics) {
  const normalized = {};

  Object.keys(calibration.features).forEach((feature) => {
    const value = Number(metrics[feature]) || 0;
    normalized[feature] = percentileOf(value, calibration.features[feature]);
  });

  return normalized;
}

/**
 * Calculate logistic regression score
 */
function calculateLogisticRegression(features) {
  // Linear combination of features
  let linearScore = MODEL_WEIGHTS.bias;

  linearScore += features.totalVolume * MODEL_WEIGHTS.totalVolume;
  linearScore +=
    features.uniqueCounterparties * MODEL_WEIGHTS.uniqueCounterparties;
  linearScore += features.assetDiversity * MODEL_WEIGHTS.assetDiversity;
  linearScore += features.nightDayRatio * MODEL_WEIGHTS.nightDayRatio;

  // Add interaction term
  const volumeCounterpartyInteraction =
    features.totalVolume * features.uniqueCounterparties;
  linearScore +=
    volumeCounterpartyInteraction * MODEL_WEIGHTS.volumeCounterpartyInteraction;

  // Apply sigmoid function to get probability (0-1)
  const probability = 1 / (1 + Math.exp(-linearScore));

  return probability;
}

/**
 * Calculate tier based on risk score
 */
function calculateTier(riskScore) {
  if (riskScore <= 30) return "TIER_1"; // Low risk - Premium access
  if (riskScore <= 70) return "TIER_2"; // Medium risk - Standard access
  return "TIER_3"; // High risk - Opportunity access
}

/**
 * Calculate model confidence.
 *
 * Confidence is dominated by HOW MUCH HISTORY we saw. The previous version used
 * only the variance of the feature vector, which produced the exact opposite of
 * the truth: a brand-new wallet is all zeros, all zeros has zero variance, so an
 * empty wallet scored the MAXIMUM confidence (95) on a profile we know nothing
 * about.
 *
 * Feature-vector homogeneity is kept as a secondary, smaller term.
 */
function calculateConfidence(features, metrics) {
  const featureValues = Object.values(features);
  const mean =
    featureValues.reduce((sum, val) => sum + val, 0) / featureValues.length;
  const variance =
    featureValues.reduce((sum, val) => sum + Math.pow(val - mean, 2), 0) /
    featureValues.length;

  // Primary term: data sufficiency (0-1).
  const quality = getDataQualityScore(metrics || {}).score / 100;

  // Secondary term: how homogeneous the feature vector is (0-1).
  const homogeneity = Math.max(0, 1 - variance);

  // No history -> near-floor confidence, regardless of how "consistent" the
  // zeros look.
  const raw = 0.75 * quality + 0.25 * homogeneity;

  return Math.round(Math.max(5, Math.min(95, raw * 100)));
}

/**
 * Calculate feature importance for explainability
 */
function calculateFeatureImportance(features, rawMetrics) {
  const importance = {};

  // Calculate weighted impact of each feature
  Object.keys(features).forEach((feature) => {
    const weight = Math.abs(MODEL_WEIGHTS[feature] || 0);
    const featureValue = features[feature];
    importance[feature] = {
      weight: Math.round(weight * 100) / 100,
      normalizedValue: Math.round(featureValue * 100) / 100,
      impact: Math.round(weight * featureValue * 100) / 100,
      rawValue: rawMetrics[feature],
      isPositive: MODEL_WEIGHTS[feature] < 0, // Negative weight = positive for safety
    };
  });

  return importance;
}

/**
 * Generate human-readable explanation
 */
function generateExplanation(riskScore, featureImportance) {
  const tier = calculateTier(riskScore);
  let explanation = [];

  // Main tier explanation
  if (tier === "TIER_1") {
    explanation.push("🟢 Low Risk - Premium pool access");
  } else if (tier === "TIER_2") {
    explanation.push("🟡 Medium Risk - Standard pool access");
  } else {
    explanation.push("🔴 High Risk - Opportunity pool access");
  }

  // Feature-based explanations
  const sortedFeatures = Object.entries(featureImportance).sort(
    (a, b) => Math.abs(b[1].impact) - Math.abs(a[1].impact)
  );

  sortedFeatures.slice(0, 2).forEach(([feature, data]) => {
    if (feature === "totalVolume") {
      if (data.isPositive && data.rawValue > 100) {
        explanation.push("✅ High transaction volume increases trust");
      } else {
        explanation.push("⚠️ Low transaction volume increases risk");
      }
    } else if (feature === "uniqueCounterparties") {
      if (data.isPositive && data.rawValue > 5) {
        explanation.push("✅ Diverse counterparties increase trust");
      } else {
        explanation.push("⚠️ Few counterparties increase risk");
      }
    } else if (feature === "assetDiversity") {
      if (data.isPositive && data.rawValue > 2) {
        explanation.push("✅ Asset diversity increases trust");
      } else {
        explanation.push("⚠️ Single asset usage increases risk");
      }
    } else if (feature === "nightDayRatio") {
      if (!data.isPositive && data.rawValue > 0.5) {
        explanation.push("⚠️ High night activity increases risk");
      }
    }
  });

  return explanation;
}

/**
 * Generate improvement recommendations
 */
function generateRecommendations(featureImportance) {
  const recommendations = [];

  Object.entries(featureImportance).forEach(([feature, data]) => {
    if (feature === "totalVolume" && data.rawValue < 50) {
      recommendations.push("📈 Increase transaction volume organically");
    }
    if (feature === "uniqueCounterparties" && data.rawValue < 3) {
      recommendations.push("🤝 Transact with different counterparties");
    }
    if (feature === "assetDiversity" && data.rawValue < 2) {
      recommendations.push("🎯 Diversify transactions with different assets");
    }
    if (feature === "nightDayRatio" && data.rawValue > 0.3) {
      recommendations.push("🌞 Make more transactions during daytime hours");
    }
  });

  if (recommendations.length === 0) {
    recommendations.push(
      "🎉 Excellent! Your risk profile is in great condition"
    );
  }

  return recommendations;
}

/**
 * Fallback rule-based calculation if ML fails
 */
function fallbackRiskCalculation(metrics) {
  let score = 50; // Start with medium risk

  // Simple rule-based adjustments
  if (metrics.totalVolume > 100) score -= 15;
  if (metrics.uniqueCounterparties > 5) score -= 10;
  if (metrics.assetDiversity > 2) score -= 10;
  if (metrics.nightDayRatio > 0.5) score += 20;

  score = Math.max(0, Math.min(100, score));

  return {
    riskScore: score,
    tier: calculateTier(score),
    confidence: 75,
    featureImportance: {},
    explanation: ["📊 Simple rule-based calculation was used"],
    recommendations: ["🔄 Try again for more detailed analysis"],
    rawMetrics: metrics,
    modelVersion: "fallback-1.0",
  };
}

/**
 * Check if we can improve score prediction with more data
 */
export function getDataQualityScore(metrics) {
  let qualityScore = 0;

  if (metrics.totalPayments > 10) qualityScore += 25;
  if (metrics.uniqueCounterparties > 3) qualityScore += 25;
  if (metrics.assetDiversity > 1) qualityScore += 25;
  // Award the final 25 points only when there is BOTH payment activity
  // AND counterparty diversity — the original code checked totalPayments > 0
  // which is always true when totalPayments > 10 is already satisfied,
  // making it impossible to ever score less than 50 via this path.
  if (metrics.totalPayments > 0 && metrics.uniqueCounterparties > 0) qualityScore += 25;

  return {
    score: qualityScore,
    isGood: qualityScore >= 75,
    needsMoreData: qualityScore < 50,
  };
}
